name: Format Check and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-formatting-and-build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: product_manager
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Run spotlessCheck
        working-directory: product-manager/product-manager-backend
        run: |
          chmod +x gradlew
          ./gradlew spotlessCheck

      - name: Build product-manager
        working-directory: product-manager/product-manager-backend
        run: ./gradlew build